###
GET http://localhost:3001/api/blog
# content-type: application/json
# Authorization: Bearer 
###
POST http://localhost:3001/api/blog
content-type: application/json
Authorization: Bearer 

{
    "title": "Hi Herizon 5",
    "author": "User_Fang",
    "url":"123",
    "likes":5}

# 
###
DELETE http://localhost:3001/api/blog/672a68e1a64bcc9b4306ecd6
content-type: application/json
Authorization: Bearer 

###
PUT http://localhost:3001/api/blog/6728eb662b3ed8bbe065e826
content-type: application/json
Authorization: Bearer 

{
    "title": "blog2",
    "author": "Fang",
    "url":"123",
    "likes":50
}

###
# USER
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "user",
    "name": "user_fang",
    "password": "123456"
}

### 
#Login
POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "root",
    "password": "salainen"
}