###
GET http://localhost:3001/api/blog
###
POST http://localhost:3001/api/blog
content-type: application/json

{
    "title": "Hi Herizon",
    "author": "User_Fang",
    "url":"123",
    "likes":5,
    "userId":"672a27e692e8e51a1bbd22ba"
}

###
DELETE http://localhost:3001/api/blog/67278f294e8cd44817e15221

###
PUT http://localhost:3001/api/blog/6728eb662b3ed8bbe065e826
content-type: application/json

{
    "title": "blog2",
    "author": "Fang",
    "url":"123",
    "likes":50
}

###
# USER
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "user_fang",
    "name": "user_fang",
    "password": "123456"
}