###
GET http://localhost:3001/api/blog
###
POST http://localhost:3001/api/blog
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3MmEyNjRiZmI3NGY5MzU1NjZjZDY4MCIsImlhdCI6MTczMDgzMjYwMCwiZXhwIjoxNzMwODM2MjAwfQ.F4zskbBUF0qAAAO0nSeW3biVdEownRKk1rngEAZ-4EU

{
    "title": "Hi Herizon 44",
    "author": "User_Fang",
    "url":"123",
    "likes":5
}

# 
###
DELETE http://localhost:3001/api/blog/672a278792e8e51a1bbd22b1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3MmEyNjRiZmI3NGY5MzU1NjZjZDY4MCIsImlhdCI6MTczMDgzMTc4NSwiZXhwIjoxNzMwODM1Mzg1fQ.W8pJdqflrGkm_RVkVpeKn-_Qlb6j3SFWkLOPsx_GK9k

###
PUT http://localhost:3001/api/blog/6728eb662b3ed8bbe065e826
content-type: application/json

{
    "title": "blog2",
    "author": "Fang",
    "url":"123",
    "likes":50
}

###
# USER
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "user_fang_11",
    "name": "user_fang",
    "password": "1"
}

### 
#Login
POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "root",
    "password": "salainen"
}