###
GET http://localhost:3001/api/blog
###
POST http://localhost:3001/api/blog
content-type: application/json

{
    "title": "blog1",
    "author": "Fang",
    "url":"123",
    "likes":5
}

###
DELETE http://localhost:3001/api/blog/67278f294e8cd44817e15221

###
PUT http://localhost:3001/api/blog/67278f294e8cd44817e15221
content-type: application/json

{
    "title": "blog2",
    "author": "Fang",
    "url":"123",
    "likes":5
}